site_name: Webová kartografie (155YWEK)
nav:
  - Charakteristika předmětu: index.md
  - Cvičení:
      - Úloha 1 – Základ HTML. Tvorba webové formy životopisu v prostředí Glitch: cviceni/cviceni1.md 
      - Základy práce s CSS. Základy JavaScriptu: cviceni/cviceni2.md
      - Úloha 2 – VS Code. Mapová aplikace v prostředí Leaflet: cviceni/cviceni3.md
      - GeoJSON. Tvorba kartogramu v Leaflet: cviceni/cviceni4.md
      - Úloha 3 – Knihovna D3.js: cviceni/cviceni5.md
      - Propojení Leaflet a D3.js. Kartodiagram: cviceni/cviceni6.md
      - Úloha 4 – Windows server (IIS) – konfigurace vlastního prostoru: cviceni/cviceni7.md
      - Úloha 5 – Základy ArcGIS JavaScript API. Práce s WebMap. Mapová aplikace pomocí ArcGIS API: cviceni/cviceni8.md
      - Pokročilejší práce s ArcGIS JavaScript API: cviceni/cviceni9.md
      - Finalizace aplikace pomocí ArcGIS JavaScript API: cviceni/cviceni10.md
      - Úloha 6 – Jednoduchá aplikace pomocí GISQuick: cviceni/cviceni11.md
  # U7 - případně U7 3D JS open source kartografická knihovna     
  # - Data: data.md

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.png
  logo: assets/favicon.svg
  icon:
    annotation: material/plus-circle
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  language: cs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: custom
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CTUGeomatics
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/geomatics.ctu
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/geomatics.ctu
copyright: <a href="https://geomatics.fsv.cvut.cz" target="_blank">Katedra geomatiky</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;2023-2024
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.tilde

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js